default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  socket: /tmp/mysql.sock
  reconnect: true
  username: root
  password:

development:
  <<: *default
  database: camellia_development

test:
  <<: *default
  database: camellia_test

production:
  <<: *default
  database: camellia_production
  username: camellia
  password: <%= ENV['CAMELLIA_DATABASE_PASSWORD'] %>
